theme: jekyll-theme-architect
title: Gary Davis' Blog
description: DotNET/PayPal Development and other Techie Stuff
show_downloads: false
google_analytics: UA-1811424-1

# Setup
name:         Gary Davis' Blog
tagline:      DotNET/PayPal Development and other Techie Stuff
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown